name: Build Luxamine APK (Self-Hosted Debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: System info and cleanup
      run: |
        echo "🔍 System Information:"
        whoami
        pwd
        echo "HOME: $HOME"
        echo "PATH: $PATH"
        df -h
        free -h
        
        # Nettoyer les anciens builds
        rm -rf .buildozer || true
        rm -rf bin || true

    - name: Install system dependencies
      run: |
        echo "📦 Installing system dependencies..."
        sudo apt-get update -qq
        sudo apt-get install -y \
          python3 python3-pip python3-dev python3-venv \
          openjdk-11-jdk \
          build-essential git wget unzip zip \
          libffi-dev libssl-dev \
          zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
          libncurses5-dev libncursesw5-dev xz-utils tk-dev \
          liblzma-dev python3-openssl \
          autotools-dev autoconf pkg-config cmake \
          libtool automake

    - name: Setup Java environment
      run: |
        echo "☕ Setting up Java..."
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH
        java -version

    - name: Install Android SDK and NDK
      run: |
        echo "📱 Installing Android SDK + NDK..."
        sudo mkdir -p /opt/android-sdk
        sudo chown $USER:$USER /opt/android-sdk
        cd /tmp
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mkdir -p /opt/android-sdk/cmdline-tools
        mv cmdline-tools /opt/android-sdk/cmdline-tools/latest

        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"

        echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
        echo "/opt/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "/opt/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Setup Python environment
      run: |
        echo "🐍 Setting up Python environment..."
        python3 --version
        pip3 --version

        pip3 install --upgrade pip
        pip3 install "setuptools<70" "packaging<24" wheel
        pip3 install buildozer==1.5.0 cython==0.29.33

        # Ajouter buildozer au PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify environment
      run: |
        echo "🔍 Environment verification:"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "PATH: $PATH"
        java -version
        python3 --version
        buildozer --version
        which buildozer
        which zip
        which javac

    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f "buildozer.spec" ]; then
          echo "📝 Creating buildozer.spec..."
          cat > buildozer.spec << 'EOF'
        [app]
        title = Luxamine
        package.name = luxamine
        package.domain = com.luxamine.editor
        source.dir = .
        version = 1.0
        requirements = python3,kivy
        orientation = portrait

        android.api = 33
        android.minapi = 21
        android.ndk = 25b
        android.archs = arm64-v8a,armeabi-v7a
        android.accept_sdk_license = True
        android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE

        [buildozer]
        log_level = 2
        warn_on_root = 1
        EOF
        fi

        echo "📋 Buildozer.spec content:"
        cat buildozer.spec

    - name: Build APK with full debug
      run: |
        echo "🚀 Starting APK build with full debug..."
        buildozer -v android debug | tee build.log

    - name: Verify APK creation
      run: |
        echo "📦 Checking for APK files..."
        find . -name "*.apk" -type f -exec ls -lh {} \;
        
        if [ -f bin/*.apk ]; then
          APK_FILE=$(ls bin/*.apk | head -1)
          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV
          echo "APK_SIZE=$(du -h "$APK_FILE" | cut -f1)" >> $GITHUB_ENV
          echo "✅ APK found: $APK_FILE ($(du -h "$APK_FILE" | cut -f1))"
        else
          echo "❌ No APK file found!"
          ls -la bin/ || echo "No bin directory"
          exit 1
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: luxamine-apk-${{ github.run_number }}
        path: bin/*.apk
        retention-days: 30
